project:
  type: website
  output-dir: docs
website:
  title: '"Good Science", "Good Analysis": a blog on the aspirations of robust science'
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: journal
    css: styles.css



